const express = require('express');
const { getAllUserRoles, getUserRoleById, createUserRole, updateUserRole, removeUserRole } = require('../controllers/usersRolesController');
const router = express.Router();
router.get('/', getAllUserRoles);
router.get('/:id', getUserRoleById);
router.get(':userId', getUserRoleByUserId);
router.post('/', createUserRole);
router.put('/:id', updateUserRole);
router.delete('/:id', removeUserRole);
module.exports = router;
